spring:
  application:
    name: SearchMovie

  config:
    import: optional:file:.properties[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: local

  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60s
    type: redis
    cache-names: searchMovie
    redis:
      time-to-live: 10m # 10ë¶„ (ms)
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

